import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { AuthUser } from "@/components/auth-user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
      >
        <SessionProvider>
          <header className="border-b">
            <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
              <a href="/" className="font-semibold tracking-tight">AI Artistry</a>
              <nav className="flex items-center gap-4 text-sm">
                <a href="/dashboard" className="hover:underline">Dashboard</a>
                <a href="/generator" className="hover:underline">Generator</a>
                <a href="/profile" className="hover:underline">Profile</a>
              </nav>
              <AuthUser />
            </div>
          </header>
          <main className="mx-auto max-w-6xl px-6 py-8">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
