import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthUser } from "@/components/auth-user";
import { Providers } from "@/components/providers";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
      >
        <Providers>
          <header className="border-b">
            <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
              <Link href="/" className="font-semibold tracking-tight">AI Artistry</Link>
              <nav className="flex items-center gap-4 text-sm">
                <Link href="/dashboard" className="hover:underline">Dashboard</Link>
                <Link href="/generator" className="hover:underline">Generator</Link>
                <Link href="/profile" className="hover:underline">Profile</Link>
              </nav>
              <AuthUser />
            </div>
          </header>
          <main className="mx-auto max-w-6xl px-6 py-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
